import React, { useState } from 'react';
import { Calculator, BookOpen } from 'lucide-react';
import './resources.css';

const guides = {
  regime: { title: 'Old vs New Regime - Which Should You Choose?', body: 'For FY 2025-26 (AY 2026-27), the new regime includes revised slabs and Section 87A relief up to the applicable threshold. The old regime allows deductions and exemptions such as 80C, 80D, HRA, and home-loan interest. Compare both using your actual income and eligible claims, then verify current rules before filing.' },
  documents: { title: 'Documents You Need Before Filing', body: 'Keep Form 16, bank interest certificates, capital-gains statements, rent receipts, home-loan certificates, and investment and insurance proofs together. Reconcile salary and TDS with Form 26AS, AIS, and TIS. Clear, complete records make the return easier to review and reduce accidental omissions.' },
  deductions: { title: 'Common Deductions Salaried Employees Miss', body: 'Check Section 80C investments, health insurance under Section 80D, eligible home-loan interest under Section 24(b), education-loan interest under Section 80E, and eligible rent claims. Each has conditions and limits, so keep the supporting certificate and use only amounts you can substantiate.' },
  risk: { title: 'Understanding Your Audit-Risk Score', body: 'A risk score is a review signal, not a finding of wrongdoing. Large claims compared with income, missing TDS, duplicate claims, and inconsistent records can increase review risk. Keep source documents, reconcile reported values, and correct mistakes before submitting a return.' },
};

function oldTax(income, deductions) { const taxable = Math.max(0, income - deductions - 50000); const slabs = [[250000,0],[250000,.05],[500000,.2],[Infinity,.3]]; let remaining=taxable, tax=0; for(const [limit,rate] of slabs){const amount=Math.min(remaining,limit); tax+=amount*rate; remaining-=amount; if(remaining<=0) break;} return tax*1.04; }
function newTax(income) { const taxable=Math.max(0,income-75000); const slabs=[[400000,0],[400000,.05],[400000,.1],[400000,.15],[400000,.2],[400000,.25],[Infinity,.3]]; let remaining=taxable,tax=0; for(const [limit,rate] of slabs){const amount=Math.min(remaining,limit);tax+=amount*rate;remaining-=amount;if(remaining<=0)break;} return tax*1.04; }
function money(value) { return `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`; }
function Field({ label, value, onChange }) { return <label className="resource-field">{label}<input type="number" min="0" value={value} onChange={event => onChange(event.target.value)} /></label>; }

function CalculatorPage({ type }) {
  const [income, setIncome] = useState('1200000'); const [deductions, setDeductions] = useState('150000'); const [basic, setBasic] = useState('600000'); const [hra, setHra] = useState('240000'); const [rent, setRent] = useState('300000'); const [metro, setMetro] = useState(true); const [liability, setLiability] = useState('100000');
  let content;
  if (type === 'income-tax') { const oldValue=oldTax(Number(income),Number(deductions)); const newValue=newTax(Number(income)); content=<><Field label="Annual gross income" value={income} onChange={setIncome} /><Field label="Eligible old-regime deductions" value={deductions} onChange={setDeductions} /><div className="resource-result"><strong>Old regime estimate</strong><b>{money(oldValue)}</b><strong>New regime estimate</strong><b>{money(newValue)}</b><span>Estimated lower option: {oldValue < newValue ? 'Old regime' : 'New regime'}</span></div></>; }
  if (type === 'hra') { const exemption=Math.max(0,Math.min(Number(hra),Number(rent)-Number(basic)*.1,Number(basic)*(metro?.5:.4))); content=<><Field label="Annual basic salary" value={basic} onChange={setBasic} /><Field label="Annual HRA received" value={hra} onChange={setHra} /><Field label="Annual rent paid" value={rent} onChange={setRent} /><label className="resource-check"><input type="checkbox" checked={metro} onChange={event => setMetro(event.target.checked)} /> Metro city</label><div className="resource-result"><strong>Estimated HRA exemption</strong><b>{money(exemption)}</b><span>Based on the minimum of HRA received, rent less 10% of basic, and the applicable city percentage.</span></div></>; }
  if (type === 'advance-tax') { const total=Math.max(0,Number(liability)); content=<><Field label="Estimated annual tax liability" value={liability} onChange={setLiability} /><div className="resource-result"><strong>15 June - 15%</strong><b>{money(total*.15)}</b><strong>15 September - cumulative 45%</strong><b>{money(total*.45)}</b><strong>15 December - cumulative 75%</strong><b>{money(total*.75)}</b><strong>15 March - cumulative 100%</strong><b>{money(total)}</b></div></>; }
  const titles={'income-tax':'Income Tax Calculator',hra:'HRA Exemption Calculator','advance-tax':'Advance Tax Calculator'};
  return <section className="resource-page"><div className="resource-title"><Calculator size={22} /><div><p className="eyebrow">Resources / Calculators</p><h1>{titles[type]}</h1></div></div><p className="resource-intro">Enter your figures for an estimate. This is informational and should be checked against current rules before filing.</p><div className="calculator-card">{content}</div></section>;
}

function GuidePage({ slug }) { const guide=guides[slug]; return <section className="resource-page guide-page"><div className="resource-title"><BookOpen size={22} /><div><p className="eyebrow">Resources / Guides</p><h1>{guide.title}</h1></div></div><p className="guide-body">{guide.body}</p></section>; }

export function ResourcesMenu({ onNavigate, hasUnreadUpdate }) { return <div className="resources-menu"><button className="resources-trigger" onClick={() => onNavigate('resource-income-tax')}><BookOpen size={16} />Resources</button><div className="resources-dropdown"><div><strong>Calculators</strong><button onClick={() => onNavigate('resource-income-tax')}>Income Tax Calculator</button><button onClick={() => onNavigate('resource-hra')}>HRA Exemption Calculator</button><button onClick={() => onNavigate('resource-advance-tax')}>Advance Tax Calculator</button></div><div><strong>Guides</strong>{Object.entries(guides).map(([slug, guide]) => <button key={slug} onClick={() => onNavigate(`guide-${slug}`)}>{guide.title}</button>)}<button onClick={() => onNavigate('changelog')}>What's New {hasUnreadUpdate && <span className="update-badge">NEW</span>}</button></div></div></div>; }
export function ResourceRoute({ step }) { if (step.startsWith('guide-')) return <GuidePage slug={step.slice(6)} />; return <CalculatorPage type={step.slice(9)} />; }
export default ResourceRoute;
