ALTER TABLE users ADD COLUMN IF NOT EXISTS employment_type VARCHAR(40) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan_aadhaar_linked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS financial_year VARCHAR(40) NOT NULL DEFAULT 'FY 2024-25 (AY 2025-26)';
ALTER TABLE users ADD COLUMN IF NOT EXISTS employer_name VARCHAR(150) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo_url VARCHAR(255) NULL;